spring.application.name=${SPRING_APP_NAME:NVD-back}

# Database Configuration - FIXED TYPOS
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration - FIXED TYPOS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

#spring.sql.init.mode=always ,use if you want to run the schema.sql in resources
jwt.secret=${JWT_SECRET}